In [1]:
import numpy as np

Creating an Array

In [145]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [146]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [148]:
np.arange(0,40,5)
#start point, end point, step point

array([ 0,  5, 10, 15, 20, 25, 30, 35])

In [149]:
np.arange(0.01,1.01,.01)
#exercise question

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [7]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.linspace(0,5,100)
# making a linear space between numbers with in the range

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [16]:
np.eye(4)
#identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.random.rand(4)

array([0.32820798, 0.60115099, 0.34582357, 0.89230978])

In [19]:
np.random.rand(4,5)

array([[0.80561371, 0.36352335, 0.08777398, 0.55595853, 0.82455705],
       [0.30957277, 0.03534714, 0.74377932, 0.03168452, 0.71032722],
       [0.41535074, 0.82696354, 0.82543592, 0.93258852, 0.73674065],
       [0.25820533, 0.00689167, 0.25898999, 0.44797356, 0.02584555]])

In [20]:
#for normal distribution
np.random.randn(3)

array([-0.14513934, -0.18685181,  1.0935802 ])

In [21]:
np.random.randn(3,3)

array([[-1.38788755,  0.64246219,  1.34451927],
       [ 0.41076899, -1.12032922, -0.59772074],
       [ 1.90604265,  0.55557867,  0.61387899]])

In [23]:
np.random.randint(1,100,10)
# random integer genegration with a starting point, ending point and how many we want

array([28, 54, 53,  4, 41, 45, 30, 14,  7, 71])

In [24]:
arr = np.arange(25)

In [28]:
ranarr = np.random.randint(0,50,9)
ranarr

array([ 5, 48, 11, 42,  1, 34, 41, 11, 32])

In [34]:
ranarr.reshape(3,3)
#reshapring from one D to what ever the user want


array([[ 5, 48, 11],
       [42,  1, 34],
       [41, 11, 32]])

In [35]:
arr.reshape(5,5)
#make sure that all the values must if into the matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
ranarr.max()

48

In [37]:
ranarr.min()

1

In [39]:
ranarr.argmax()
#index

1

In [41]:
arr.shape

(25,)

In [42]:
arr.dtype

dtype('int32')

In [43]:
ranarr.dtype

dtype('int32')

In [44]:
arr = np.arange(0,11)

In [45]:
arr[8]
# index valu extraction

8

In [48]:
arr[1:5]
#SLICING (HEADACHE)
#start index : stop index

array([1, 2, 3, 4])

In [49]:
arr[:6]
#ending to 6

array([0, 1, 2, 3, 4, 5])

In [50]:
arr[5:]
#start with 5 end til the last index

array([ 5,  6,  7,  8,  9, 10])

In [51]:
arr[0:5] = 100

In [52]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [53]:
slice_of_arr = arr[0:6]

In [54]:
slice_of_arr[:]

array([100, 100, 100, 100, 100,   5])

In [57]:
slice_of_arr[:] = 99

In [59]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [60]:
arr = np.arange(0,11)

In [62]:
arr_copy = arr.copy()
#to copy an array

In [66]:
arr_copy
# now u can play how ever u want to

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
arr_copy[:] = 120

In [68]:
arr_copy

array([120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120])

In [69]:
arr
# main array will be the same

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

indexing for 2-D array

In [71]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [77]:
#double bracked format
arr_2d[0][0] 
#arr_2d[0,0]
# first row and first column

5

In [87]:
arr_2d[1,1]
#to get 25 from the array
# use this more

25

In [97]:
#sub matrix extraction using slice
arr_2d[:2,1:]
# first get two rows and then start from column one

array([[10, 15],
       [25, 30]])

In [100]:
#conditional selection
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [105]:
boolarr = arr > 5
boolarr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [104]:
arr[boolarr]
#get all true values

array([ 6,  7,  8,  9, 10])

In [106]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [108]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [112]:
#let's extract 23,24,25
#let's use conditions first
one = arr_2d[arr_2d>22]
two = one[one<26]
two

array([23, 24, 25])

In [118]:
#let's extract sub matrix
arr_2d[1:4,2:5]
# don't think i did at one short... trial and error method, took me 4 turns to do


array([[12, 13, 14],
       [22, 23, 24],
       [32, 33, 34]])

In [120]:
#numpy operations
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [122]:
arr + arr
#add two arrays

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [123]:
#scalar multiplication
#mulitple a number to each element in the second array
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [124]:
1/arr
#it's very good with handling errors
# we divided 1 with 0 as the first digit but it just gave inf and continued 

C:\Users\suman\AppData\Local\Temp\ipykernel_18744\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [125]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [126]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [127]:
np.max(arr)

10

In [129]:
np.sin(arr)
#cos #tan

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [137]:
np.random.randint(0,1,20)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [140]:
#add a whole column
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [144]:
arr.sum(axis = 0)
# 0 = COLUMN AND 1 = AXIS


array([ 9, 12, 15])

we did it 🎉🎉🎉